### ISSUE TITLE
Unlock core wallet 

### ISSUE THREAD

**Issue by hakork70** [X9Developers/block-explorer#400]

**Comment by AlexITC** [comment]
Please open the issue in https://github.com/X9Developers/XSN/issues, this repository is just about the block explorer.

Good luck.

**Comment by hakork70** [comment]
How can I contact the juri.. Telegram or mail...

1 Ara 2021 Çar 20:19 tarihinde Alexis Hernandez ***@***.***>
şunu yazdı:
